import { BRAND_ACCENT_NAME } from "@repo/ui";
import type { Locale } from "./i18n";

/**
 * Interface copy in French, worded with the glossary (CONTEXT.md). Its shape is the one
 * every language must give (`Strings`): a key missing or added in another language fails
 * the typecheck, and the test of the strings.
 */
const fr = {
  /** Number conventions of the language (Intl locale). */
  locale: "fr-FR",
  generator: "Générateur de baseplates",
  description:
    "Générateur gratuit et open source de baseplates Gridfinity à la mesure de votre tiroir, calculées dans le navigateur.",
  // Top bar and menu
  share: "Partager",
  reset: "Réinitialiser",
  donate: "Offrir un café",
  comingSoon: "Bientôt disponible",
  newTab: "s'ouvre dans un nouvel onglet",
  parameters: "Paramètres",
  menu: "Menu",
  actions: "Actions",
  linkCopied: "Lien copié",
  copyFailed: "Copie impossible : copiez le lien ci-dessous.",
  resetTitle: "Réinitialiser les réglages ?",
  resetDescription:
    "La baseplate revient aux réglages par défaut. Vos paramètres sont conservés : langue, unités, buse, hauteur de couche, largeur de ligne, plateau et couleur de l'aperçu.",
  cancel: "Annuler",
  language: "Langue",
  units: "Unités",
  unitNames: { mm: "mm", in: "pouces" },
  unitsHint: "Pour les cotes du tiroir et des marges. Les autres longueurs, vis comprises, restent en mm.",
  previewColor: "Couleur de l'aperçu",
  previewColors: {
    brand: BRAND_ACCENT_NAME.fr as string,
    white: "Blanc",
    pebble: "Galet",
    graphite: "Graphite",
    sand: "Sable",
  },
  print: "Impression",
  nozzle: "Buse",
  nozzleHint: "Choisir une buse règle la largeur de ligne sur son diamètre.",
  layerHeight: "Hauteur de couche",
  thinnerLayer: "Couche plus fine",
  thickerLayer: "Couche plus épaisse",
  lineWidth: "Largeur de ligne",
  narrowerLine: "Ligne plus fine",
  widerLine: "Ligne plus large",
  buildPlate: "Plateau",
  buildPlateHint: "Surface utile du plateau de votre imprimante.",
  buildPlateWidth: "Largeur du plateau",
  narrowerPlate: "Plateau moins large",
  widerPlate: "Plateau plus large",
  buildPlateDepth: "Profondeur du plateau",
  shallowerPlate: "Plateau moins profond",
  deeperPlate: "Plateau plus profond",
  // Statistics
  statistics: "Statistiques",
  statCells: "Cellules",
  statMargin: "Marge",
  statHeight: "Hauteur",
  statVolume: "Matière",
  statScrews: "Vis",
  statMagnets: "Aimants",
  /** Magnets to buy: how many, and their size (the holes take 6 × 2 mm discs). */
  magnetCount: (count: string) => `${count} (Ø 6 × 2 mm)`,
  noMagnet: "aucun",
  statPieces: "Pièces",
  statClips: "Clips",
  none: "aucune",
  noClip: "aucun",
  computing: "calcul en cours",
  layers: (count: number, layerHeight: string) => `${count} couches de ${layerHeight} mm`,
  margins: (left: string, right: string, back: string, front: string, unit: string) =>
    `gauche ${left}, droite ${right}, arrière ${back}, avant ${front} ${unit}`,
  fits: "tient",
  doesNotFit: "ne tient pas",
  plateTooSmall: (plate: string) =>
    `Même découpée, une pièce dépasse votre plateau (${plate}) dans les deux sens : une cellule et sa marge n'y tiennent pas. Réduisez la marge ou la taille des cellules, ou corrigez la taille du plateau dans les paramètres.`,
  plateTooSmallShort: "Ne tient pas sur le plateau",
  narrowMargin: (margin: string, lines: string) =>
    `Une marge de ${margin} mm est plus étroite que deux largeurs de ligne (${lines} mm) : elle s'imprimera mal. Élargissez-la ou supprimez-la.`,
  // Preview
  recenter: "Recentrer la vue",
  webglUnavailable: "Aperçu 3D indisponible : WebGL est désactivé dans ce navigateur.",
  // Settings panel
  settings: "Réglages",
  close: "Fermer",
  dimensions: "Dimensions",
  /** Read by screen readers before the dimensions of the readout. */
  dimensionsPrefix: "Dimensions : ",
  cells: (columns: number, rows: number) => `${columns} × ${rows} cellules`,
  height: "hauteur",
  size: "Taille",
  sizeMode: "Mode de taille",
  sizeDrawer: "Tiroir",
  sizeCells: "Nombre de cellules",
  drawerHint: "Cotes intérieures du tiroir : la baseplate le remplit.",
  drawerWidth: "Largeur",
  narrowerDrawer: "Tiroir moins large",
  widerDrawer: "Tiroir plus large",
  drawerDepth: "Profondeur",
  shallowerDrawer: "Tiroir moins profond",
  deeperDrawer: "Tiroir plus profond",
  marginWidth: "Marge en largeur",
  lessMarginWidth: "Moins de marge en largeur",
  moreMarginWidth: "Plus de marge en largeur",
  marginDepth: "Marge en profondeur",
  lessMarginDepth: "Moins de marge en profondeur",
  moreMarginDepth: "Plus de marge en profondeur",
  withMargin: (width: string, depth: string, unit: string) => `marge ${width} × ${depth} ${unit}`,
  withoutMargin: "sans marge",
  alignment: "Alignement",
  alignmentHint: "Où placer la grille quand la marge ne tombe pas juste : la marge prend le reste.",
  alignments: {
    tl: "Arrière gauche",
    t: "Arrière",
    tr: "Arrière droite",
    l: "Gauche",
    c: "Centre",
    r: "Droite",
    bl: "Avant gauche",
    b: "Avant",
    br: "Avant droite",
  },
  baseplateType: "Type",
  baseplateTypes: { normal: "Normal", tray: "Tray", skeleton: "Skeleton", clickbase: "CLICKbase" },
  baseplateTypeNames: { normal: "Normal, sans fond", tray: "Tray, fond plein", skeleton: "Skeleton, allégée", clickbase: "CLICKbase, bacs clipsés" },
  normalHint: "La grille ajourée, sans fond, posée au fond du tiroir : chaque bac est tenu sur tout son tour.",
  trayHint: (floor: string, gap: string) =>
    `La grille sur un fond plein de ${floor} mm : rien ne passe dessous, pour un bureau, une étagère ou de petites pièces. Les poches montent de ${floor} mm, plus ${gap} mm de jeu : le bac reste assis sur ses pentes, sans toucher le fond.`,
  skeletonHint: (band: string) =>
    `Les murets sont entaillés entre les croisements, jusqu'à une bande de ${band} mm : seuls des poteaux au profil complet restent aux coins des cellules, et le bac n'est guidé que par ses 4 coins. Environ deux fois moins de matière. Le tour de la grille reste entier. Pas de clips.`,
  clickbaseHint: (interference: string) =>
    `Deux lamelles dans la paroi de chaque côté de poche serrent le pied du bac de ${interference} mm : il s'enclenche et tient sans aimant. Le premier bac casse les fines toiles qui portent les lamelles à l'impression. Le milieu des côtés reste plein pour les clips. D'après CLICKbase Refined (ZeroCtrl) et CLICKbase (John Hall), sous licence CC BY-NC-SA : pas d'usage commercial.`,
  clickbaseWarning: "CLICKbase : imprimez en PETG, pas en PLA, qui flue et ne serre plus les bacs. Générateur de parois Arachne, buse de 0,4 mm.",
  typeVolumesHint: "Matière de la baseplate avec chaque type, mesurée sur le maillage.",
  margin: "Marge",
  marginShapes: { frame: "Cadre", cells: "Cellules", brackets: "Équerres" },
  marginShapeNames: { frame: "Cadre à traverses", cells: "Cellules tronquées", brackets: "Équerres de coin" },
  marginShapeHints: {
    frame: "Un mur de 2 mm le long du tiroir, relié à chaque muret par une traverse. Le plus économe qui s'appuie sur tout le tour du tiroir.",
    cells: "La grille continue jusqu'au bord du tiroir, en cellules coupées par un mur extérieur, à la hauteur de la grille. Le plus beau, mais le plus de matière.",
    brackets: "Une équerre de 2 mm à chaque coin, et une en T sur les côtés de plus de 4 cellules. Le moins de matière, mais la baseplate ne s'appuie sur le tiroir qu'aux équerres.",
  },
  marginVolumesHint: "Matière de la baseplate avec chaque forme, mesurée sur le maillage.",
  noMarginHint: "La grille remplit le tiroir : pas de marge, la forme ne change rien.",
  screws: "Vis",
  screwsOff: "Désactivées",
  screwsSummary: (count: string, shank: string, head: string) => `${count} vis, tige ${shank} mm, tête ${head} mm`,
  screwsOffHint: "Trous fraisés pour visser la baseplate au fond du tiroir, une vis à chaque intersection intérieure de la grille.",
  screwShank: "Ø tige",
  screwHead: "Ø tête",
  screwsHint: "La tête se loge dans le croisement des murets, sous les pentes des poches. Le jeu des trous se règle dans Avancé.",
  clips: "Clips",
  clipsOff: "Désactivés",
  clipsUncut: "Sans découpe",
  clipsSummary: (count: string) => `${count} clips à imprimer`,
  clipsHint:
    "Agrafes en U qui relient les pièces : elles s'enfoncent par-dessous dans le pied des murets, à cheval sur chaque coupe, et ne se voient pas de dessus. Elles sont dans le fichier, avec les pièces, couchées sur le côté.",
  clipsUncutHint: "La baseplate tient sur votre plateau : pas de découpe, donc pas de clip.",
  clipsOffHint: "Sans clips, les pièces sont posées bout à bout, et le tiroir les tient.",
  clipsSkeleton: "Sans objet en Skeleton",
  clipsSkeletonHint:
    "Pas de clips en Skeleton : le milieu des murets, où ils se logent, est entaillé. Les pièces sont posées bout à bout, et le tiroir les tient.",
  stack: "Empiler les pièces",
  stackOff: "Désactivé",
  stackSummary: (pieces: number, stacks: number) => (stacks === 1 ? `${pieces} pièces en une pile` : `${pieces} pièces en ${stacks} piles`),
  /** Why the pieces cannot be stacked, in the summary of the family. */
  stackBlockedShort: {
    "single-piece": "Sans découpe",
    "low-margin": "Marge trop basse",
    tray: "Sans objet en Tray",
    clickbase: "Sans objet en CLICKbase",
  },
  stackBlocked: {
    "single-piece": "La baseplate tient sur votre plateau : une seule pièce, rien à empiler.",
    "low-margin":
      "La marge en cadre ou en équerres fait 2 mm de haut : sous une pièce retournée, elle commencerait en l'air, loin au-dessus de la pièce du dessous. Pour empiler, prenez la marge en cellules tronquées, pleine hauteur.",
    tray: "Retourné, le fond d'un Tray ponterait toute la poche, et en s'affaissant il remonterait vers le pied du bac, posé 0,2 mm au-dessus.",
    clickbase: "Les toiles d'un CLICKbase portent ses lamelles quand il est imprimé à l'endroit ; retourné, elles s'imprimeraient sur les lamelles et y souderaient.",
  },
  stackUseCells: "Passer aux cellules tronquées",
  stackHint: (pitch: string) =>
    `Toutes les pièces en une impression, sans multimatériau : la première à l'endroit, les autres retournées sur celle du dessous, une couche d'air entre deux (pas de ${pitch} mm). Les clips restent à part.`,
  stackPlan: (index: number, pieces: string, height: string) => `Pile ${index} : pièces ${pieces}, ${height} mm`,
  stackApart:
    "Une pièce ne se pose que sur une pièce qui la porte (même grille, murs de marge l'un sur l'autre) : sinon, elle commence une autre pile.",
  stackLayerWarning: (layer: string) =>
    `Couches de ${layer} mm : au-delà de 0,2 mm, PrusaSlicer et OrcaSlicer signalent la couche vide entre deux pièces.`,
  stackSkeletonWarning: "En Skeleton, la bande des murets entaillés est imprimée en pont entre deux poteaux, sur chaque pièce retournée.",
  stackEars: "Oreilles aux coins",
  stackEarsHint: "Un disque d'une couche sur chaque coin de la pièce du bas, contre le décollement. À couper au cutter.",
  stackPins: "Pions de 0,8 mm",
  stackPinsHint: "Une colonne fine traverse la pile à chaque coin que les pièces partagent, et une oreille la relie à chacune : les coins ne se soulèvent pas.",
  stackTips:
    "Au trancheur : même hauteur de couche, sans couches variables ; désactivez le ralentissement des surplombs. Séparez les pièces à la lame, en faisant le tour.",
  stackPreference: "Préférence de ce navigateur : elle n'entre pas dans le lien de partage.",
  advanced: "Avancé",
  drawerGap: "Jeu au tiroir",
  lessGap: "Moins de jeu",
  moreGap: "Plus de jeu",
  drawerGapHint: "Retiré à la largeur et à la profondeur du tiroir, pour que la baseplate y entre sans forcer.",
  holeGap: "Jeu des trous",
  lessHoleGap: "Moins de jeu aux trous",
  moreHoleGap: "Plus de jeu aux trous",
  holeGapHint: "Ajouté au Ø de la tige et de la tête des vis, et au Ø des logements d'aimants, pour qu'ils entrent sans forcer.",
  advancedDefaults: "Valeurs par défaut",
  /** The advanced settings that differ from their default, in the order of the family. */
  advancedChanges: {
    cellSize: (value: string) => `cellule ${value} mm`,
    outerRadius: (value: string) => `coins ${value} mm`,
    bottomChamfer: (value: string) => `chanfrein ${value} mm`,
    drawerGap: (value: string) => `jeu au tiroir ${value} mm`,
    holeGap: (value: string) => `jeu des trous ${value} mm`,
  },
  advancedWarning:
    "Réglages avancés modifiés : hors des valeurs par défaut, les bacs standard risquent de ne plus s'emboîter.",
  cellSize: "Taille de cellule",
  cellSizeHint: "42 mm dans le standard Gridfinity. La poche garde le profil du standard : seule sa largeur suit la cellule.",
  outerRadius: "Rayon des coins",
  outerRadiusHint: "Coins extérieurs de la baseplate, jamais plus que la moitié de son plus petit côté.",
  bottomChamfer: "Chanfrein du dessous",
  bottomChamferHint: "À 45° sur tout le pourtour du dessous, marge comprise, contre le pied d'éléphant de la première couche.",
  columns: "Colonnes",
  fewerColumns: "Une colonne de moins",
  moreColumns: "Une colonne de plus",
  rows: "Rangées",
  fewerRows: "Une rangée de moins",
  moreRows: "Une rangée de plus",
  pocketProfile: "Profil de poche",
  hybrid: "Hybride",
  hybridDescription: "4,6 mm. Marche de 0,35 mm sous les pentes : le bac est bien assis, sans jeu.",
  flush: "Ras",
  flushDescription: "4,25 mm, sans marche : le bac repose sur le fond du tiroir, avec un léger jeu.",
  recommended: "Recommandé",
  testKit: "Kit de test",
  testKitHint: (size: string) =>
    `Une baseplate 1 × 2 de ${size} : une cellule hybride à l'avant, une cellule ras à l'arrière, 0,35 mm plus basse. Essayez-y vos bacs avant d'imprimer une grande baseplate.`,
  downloadTestKit: "Télécharger le kit de test",
  preparingTestKit: "Préparation du kit…",
  // Download
  download: { "3mf": "Télécharger le 3MF", stl: "Télécharger le STL" },
  preparing: { "3mf": "Préparation du 3MF…", stl: "Préparation du STL…" },
  otherFormats: "Autres formats",
  threeMfDescription: "Recommandé : s'ouvre dans le trancheur, avec le lien de ses réglages.",
  stlDescription: "Pour les trancheurs qui ne lisent pas le 3MF. Découpée, la baseplate vient en zip, un fichier par pièce, plus les clips.",
  /** Name of a piece of a cut baseplate in the 3MF; `{n}` is its number, engraved under it. */
  pieceName: "pièce {n}",
  /** Name of the clips of a cut baseplate in the 3MF; `{n}` is how many. */
  clipName: "clip × {n}",
  /** Name of a stack of pieces in the 3MF; `{n}` is its number, `{pieces}` the numbers of its pieces from the bottom up. */
  stackName: "pile {n} : pièces {pieces}",
  // Errors
  computeFailed: "Le calcul de la baseplate a échoué. Modifiez un réglage pour réessayer.",
  exportFailed: "Le téléchargement a échoué. Réessayez.",
};

/** The interface copy of one language. */
export type Strings = typeof fr;

const en: Strings = {
  locale: "en-US",
  generator: "Baseplate generator",
  description:
    "Free and open-source generator of Gridfinity baseplates sized for your drawer, computed in your browser.",
  // Top bar and menu
  share: "Share",
  reset: "Reset",
  donate: "Buy me a coffee",
  comingSoon: "Coming soon",
  newTab: "opens in a new tab",
  parameters: "Parameters",
  menu: "Menu",
  actions: "Actions",
  linkCopied: "Link copied",
  copyFailed: "Could not copy: copy the link below.",
  resetTitle: "Reset the settings?",
  resetDescription:
    "The baseplate goes back to the default settings. Your parameters are kept: language, units, nozzle, layer height, line width, build plate and preview color.",
  cancel: "Cancel",
  language: "Language",
  units: "Units",
  unitNames: { mm: "mm", in: "inches" },
  unitsHint: "For the drawer and the margins. Every other length, screws included, stays in mm.",
  previewColor: "Preview color",
  previewColors: {
    brand: BRAND_ACCENT_NAME.en,
    white: "White",
    pebble: "Pebble",
    graphite: "Graphite",
    sand: "Sand",
  },
  print: "Print",
  nozzle: "Nozzle",
  nozzleHint: "Choosing a nozzle sets the line width to its diameter.",
  layerHeight: "Layer height",
  thinnerLayer: "Thinner layer",
  thickerLayer: "Thicker layer",
  lineWidth: "Line width",
  narrowerLine: "Narrower line",
  widerLine: "Wider line",
  buildPlate: "Build plate",
  buildPlateHint: "Usable area of your printer's build plate.",
  buildPlateWidth: "Build plate width",
  narrowerPlate: "Narrower build plate",
  widerPlate: "Wider build plate",
  buildPlateDepth: "Build plate depth",
  shallowerPlate: "Shallower build plate",
  deeperPlate: "Deeper build plate",
  // Statistics
  statistics: "Statistics",
  statCells: "Cells",
  statMargin: "Margin",
  statHeight: "Height",
  statVolume: "Material",
  statScrews: "Screws",
  statMagnets: "Magnets",
  magnetCount: (count: string) => `${count} (Ø 6 × 2 mm)`,
  noMagnet: "none",
  statPieces: "Pieces",
  statClips: "Clips",
  none: "none",
  noClip: "none",
  computing: "computing",
  layers: (count: number, layerHeight: string) => `${count} layers of ${layerHeight} mm`,
  margins: (left: string, right: string, back: string, front: string, unit: string) =>
    `left ${left}, right ${right}, back ${back}, front ${front} ${unit}`,
  fits: "fits",
  doesNotFit: "does not fit",
  plateTooSmall: (plate: string) =>
    `Even cut, a piece is larger than your build plate (${plate}) both ways: a cell and its margin do not fit on it. Reduce the margin or the cell size, or correct the size of the build plate in the parameters.`,
  plateTooSmallShort: "Does not fit on the build plate",
  narrowMargin: (margin: string, lines: string) =>
    `A margin of ${margin} mm is narrower than two line widths (${lines} mm): it will print poorly. Widen it or remove it.`,
  // Preview
  recenter: "Recenter the view",
  webglUnavailable: "3D preview unavailable: WebGL is turned off in this browser.",
  // Settings panel
  settings: "Settings",
  close: "Close",
  dimensions: "Dimensions",
  dimensionsPrefix: "Dimensions: ",
  cells: (columns: number, rows: number) => `${columns} × ${rows} cells`,
  height: "height",
  size: "Size",
  sizeMode: "Size mode",
  sizeDrawer: "Drawer",
  sizeCells: "Number of cells",
  drawerHint: "Inside dimensions of the drawer: the baseplate fills it.",
  drawerWidth: "Width",
  narrowerDrawer: "Narrower drawer",
  widerDrawer: "Wider drawer",
  drawerDepth: "Depth",
  shallowerDrawer: "Shallower drawer",
  deeperDrawer: "Deeper drawer",
  marginWidth: "Margin in width",
  lessMarginWidth: "Less margin in width",
  moreMarginWidth: "More margin in width",
  marginDepth: "Margin in depth",
  lessMarginDepth: "Less margin in depth",
  moreMarginDepth: "More margin in depth",
  withMargin: (width: string, depth: string, unit: string) => `margin ${width} × ${depth} ${unit}`,
  withoutMargin: "no margin",
  alignment: "Alignment",
  alignmentHint: "Where the grid goes when the margin does not fall evenly: the margin takes the rest.",
  alignments: {
    tl: "Back left",
    t: "Back",
    tr: "Back right",
    l: "Left",
    c: "Center",
    r: "Right",
    bl: "Front left",
    b: "Front",
    br: "Front right",
  },
  baseplateType: "Type",
  baseplateTypes: { normal: "Normal", tray: "Tray", skeleton: "Skeleton", clickbase: "CLICKbase" },
  baseplateTypeNames: { normal: "Normal, open", tray: "Tray, solid floor", skeleton: "Skeleton, lightened", clickbase: "CLICKbase, bins click in" },
  normalHint: "The open grid, without a floor, laid on the bottom of the drawer: each bin is held all around.",
  trayHint: (floor: string, gap: string) =>
    `The grid on a solid floor of ${floor} mm: nothing goes through, for a desk, a shelf or small parts. The pockets rise by ${floor} mm, plus ${gap} mm of gap: the bin stays seated on its slopes, clear of the floor.`,
  skeletonHint: (band: string) =>
    `The walls between pockets are notched between their crossings, down to a band of ${band} mm: only posts of the whole profile stay at the corners of the cells, and the bin is guided by its 4 corners only. About half the material. The rim of the grid stays whole. No clips.`,
  clickbaseHint: (interference: string) =>
    `Two lamellas in the wall of each side of a pocket grip the foot of the bin by ${interference} mm: it clicks in and stays, without magnets. The first bin breaks the thin webs that hold the lamellas up in print. The middle of each side stays whole for the clips. After CLICKbase Refined (ZeroCtrl) and CLICKbase (John Hall), under the CC BY-NC-SA license: no commercial use.`,
  clickbaseWarning: "CLICKbase: print in PETG, not PLA, which creeps and stops gripping the bins. Arachne wall generator, 0.4 mm nozzle.",
  typeVolumesHint: "Material of the baseplate of each type, measured on the mesh.",
  margin: "Margin",
  marginShapes: { frame: "Frame", cells: "Cells", brackets: "Brackets" },
  marginShapeNames: { frame: "Frame of crossbars", cells: "Truncated cells", brackets: "Corner brackets" },
  marginShapeHints: {
    frame: "A 2 mm wall along the drawer, tied to the grid by a crossbar in line with each wall between pockets. The cheapest that bears on the whole drawer outline.",
    cells: "The grid goes on up to the edge of the drawer, in cells cut by an outer wall, as high as the grid. The best-looking, but the most material.",
    brackets: "A 2 mm bracket at each corner, and a T one on the sides longer than 4 cells. The least material, but the baseplate bears on the drawer at the brackets only.",
  },
  marginVolumesHint: "Material of the baseplate with each shape, measured on the mesh.",
  noMarginHint: "The grid fills the drawer: no margin, the shape changes nothing.",
  screws: "Screws",
  screwsOff: "Off",
  screwsSummary: (count: string, shank: string, head: string) => `${count} screws, shank ${shank} mm, head ${head} mm`,
  screwsOffHint: "Countersunk holes to screw the baseplate to the bottom of the drawer, one screw at each inner intersection of the grid.",
  screwShank: "Shank Ø",
  screwHead: "Head Ø",
  screwsHint: "The head sits where the walls between pockets cross, under the slopes of the pockets. The hole gap is set in Advanced.",
  clips: "Clips",
  clipsOff: "Off",
  clipsUncut: "No cut",
  clipsSummary: (count: string) => `${count} clips to print`,
  clipsHint:
    "U-shaped staples that join the pieces: they push up from below into the foot of the walls, astride each cut, and do not show from above. They come in the file with the pieces, lying on their side.",
  clipsUncutHint: "The baseplate fits on your build plate: no cut, so no clip.",
  clipsOffHint: "Without clips, the pieces lie end to end, and the drawer holds them.",
  clipsSkeleton: "Not with Skeleton",
  clipsSkeletonHint:
    "No clips with Skeleton: the middle of the walls, where they sit, is notched. The pieces lie end to end, and the drawer holds them.",
  stack: "Stack the pieces",
  stackOff: "Off",
  stackSummary: (pieces: number, stacks: number) => (stacks === 1 ? `${pieces} pieces in one stack` : `${pieces} pieces in ${stacks} stacks`),
  stackBlockedShort: {
    "single-piece": "No cut",
    "low-margin": "Margin too low",
    tray: "Not with Tray",
    clickbase: "Not with CLICKbase",
  },
  stackBlocked: {
    "single-piece": "The baseplate fits on your build plate: a single piece, nothing to stack.",
    "low-margin":
      "A frame or bracket margin is 2 mm high: under a piece upside down, it would start in the air, well above the piece beneath. To stack, choose the margin in truncated cells, full height.",
    tray: "Upside down, the floor of a Tray would bridge the whole pocket, and its sag would rise towards the foot of the bin, which sits 0.2 mm above it.",
    clickbase: "The webs of a CLICKbase hold its lamellas up when it prints right side up; upside down, they would print on the lamellas and weld to them.",
  },
  stackUseCells: "Switch to truncated cells",
  stackHint: (pitch: string) =>
    `Every piece in one print, without multi-material: the first right side up, the others upside down on the one beneath, one layer of air between two (pitch of ${pitch} mm). The clips stay apart.`,
  stackPlan: (index: number, pieces: string, height: string) => `Stack ${index}: pieces ${pieces}, ${height} mm`,
  stackApart: "A piece only goes on a piece that holds it (same grid, margin walls on each other): otherwise it starts another stack.",
  stackLayerWarning: (layer: string) => `Layers of ${layer} mm: above 0.2 mm, PrusaSlicer and OrcaSlicer report the empty layer between two pieces.`,
  stackSkeletonWarning: "With Skeleton, the band of the notched walls prints as a bridge between two posts, on each piece upside down.",
  stackEars: "Corner ears",
  stackEarsHint: "A one-layer disc on each corner of the bottom piece, against lifting. Cut off with a knife.",
  stackPins: "0.8 mm pins",
  stackPinsHint: "A thin column goes through the stack at each corner the pieces share, and an ear ties it to each of them: the corners do not lift.",
  stackTips: "In the slicer: the same layer height, no variable layers; turn off the slowdown for overhangs. Separate the pieces with a blade, all the way round.",
  stackPreference: "A preference of this browser: it is not in the share link.",
  advanced: "Advanced",
  drawerGap: "Drawer gap",
  lessGap: "Less gap",
  moreGap: "More gap",
  drawerGapHint: "Taken off the width and depth of the drawer, so that the baseplate goes in without forcing.",
  holeGap: "Hole gap",
  lessHoleGap: "Less gap at the holes",
  moreHoleGap: "More gap at the holes",
  holeGapHint: "Added to the shank and head Ø of the screws, and to the Ø of the magnet holes, so that they go in without forcing.",
  advancedDefaults: "Default values",
  advancedChanges: {
    cellSize: (value: string) => `cell ${value} mm`,
    outerRadius: (value: string) => `corners ${value} mm`,
    bottomChamfer: (value: string) => `chamfer ${value} mm`,
    drawerGap: (value: string) => `drawer gap ${value} mm`,
    holeGap: (value: string) => `hole gap ${value} mm`,
  },
  advancedWarning: "Advanced settings changed: away from the default values, standard bins may no longer fit.",
  cellSize: "Cell size",
  cellSizeHint: "42 mm in the Gridfinity standard. The pocket keeps the profile of the standard: only its width follows the cell.",
  outerRadius: "Corner radius",
  outerRadiusHint: "Outer corners of the baseplate, never more than half its smallest side.",
  bottomChamfer: "Bottom chamfer",
  bottomChamferHint: "At 45° all around the bottom, margin included, against the elephant's foot of the first layer.",
  columns: "Columns",
  fewerColumns: "One column fewer",
  moreColumns: "One column more",
  rows: "Rows",
  fewerRows: "One row fewer",
  moreRows: "One row more",
  pocketProfile: "Pocket profile",
  hybrid: "Hybrid",
  hybridDescription: "4.6 mm. A 0.35 mm step under the slopes: the bin is well seated, without play.",
  flush: "Flush",
  flushDescription: "4.25 mm, without the step: the bin rests on the bottom of the drawer, with slight play.",
  recommended: "Recommended",
  testKit: "Test kit",
  testKitHint: (size: string) =>
    `A 1 × 2 baseplate of ${size}: a hybrid cell at the front, a flush cell at the back, 0.35 mm lower. Try your bins in it before printing a large baseplate.`,
  downloadTestKit: "Download the test kit",
  preparingTestKit: "Preparing the kit…",
  // Download
  download: { "3mf": "Download the 3MF", stl: "Download the STL" },
  preparing: { "3mf": "Preparing the 3MF…", stl: "Preparing the STL…" },
  otherFormats: "Other formats",
  threeMfDescription: "Recommended: opens in the slicer, with the link to its settings.",
  stlDescription: "For the slicers that cannot read 3MF. Cut, the baseplate comes as a zip, one file per piece, and the clips.",
  pieceName: "piece {n}",
  clipName: "clip × {n}",
  stackName: "stack {n}: pieces {pieces}",
  // Errors
  computeFailed: "The baseplate could not be computed. Change a setting to try again.",
  exportFailed: "The download failed. Try again.",
};

/** The interface copy of every language. */
export const STRINGS: Record<Locale, Strings> = { fr, en };
