import { BRAND_ACCENT_NAME } from "@repo/ui";

/**
 * Interface copy, worded with the glossary (CONTEXT.md). French only for now: English and
 * language switching arrive with #14.
 */
export const strings = {
  locale: "fr-FR",
  generator: "Générateur de baseplates",
  // Top bar and menu
  share: "Partager",
  reset: "Réinitialiser",
  donate: "Offrir un café",
  comingSoon: "Bientôt disponible",
  newTab: "s'ouvre dans un nouvel onglet",
  parameters: "Paramètres",
  menu: "Menu",
  actions: "Actions",
  linkCopied: "Lien copié",
  copyFailed: "Copie impossible : copiez le lien ci-dessous.",
  resetTitle: "Réinitialiser les réglages ?",
  resetDescription:
    "La baseplate revient aux réglages par défaut. Vos paramètres sont conservés : buse, hauteur de couche, largeur de ligne, plateau et couleur de l'aperçu.",
  cancel: "Annuler",
  previewColor: "Couleur de l'aperçu",
  previewColors: {
    brand: BRAND_ACCENT_NAME.fr,
    white: "Blanc",
    pebble: "Galet",
    graphite: "Graphite",
    sand: "Sable",
  },
  print: "Impression",
  nozzle: "Buse",
  nozzleHint: "Choisir une buse règle la largeur de ligne sur son diamètre.",
  layerHeight: "Hauteur de couche",
  thinnerLayer: "Couche plus fine",
  thickerLayer: "Couche plus épaisse",
  lineWidth: "Largeur de ligne",
  narrowerLine: "Ligne plus fine",
  widerLine: "Ligne plus large",
  buildPlate: "Plateau",
  buildPlateHint: "Surface utile du plateau de votre imprimante.",
  buildPlateWidth: "Largeur du plateau",
  narrowerPlate: "Plateau moins large",
  widerPlate: "Plateau plus large",
  buildPlateDepth: "Profondeur du plateau",
  shallowerPlate: "Plateau moins profond",
  deeperPlate: "Plateau plus profond",
  // Statistics
  statistics: "Statistiques",
  statCells: "Cellules",
  statMargin: "Marge",
  statHeight: "Hauteur",
  statVolume: "Matière",
  statScrews: "Vis",
  statPieces: "Pièces",
  none: "aucune",
  computing: "calcul en cours",
  layers: (count: number, layerHeight: string) => `${count} couches de ${layerHeight} mm`,
  margins: (left: string, right: string, back: string, front: string) =>
    `gauche ${left}, droite ${right}, arrière ${back}, avant ${front} mm`,
  fits: "tient",
  doesNotFit: "ne tient pas",
  plateTooSmall: (plate: string) =>
    `La baseplate dépasse votre plateau (${plate}) dans les deux sens. Réduisez-la, ou corrigez la taille du plateau dans les paramètres.`,
  plateTooSmallShort: "Ne tient pas sur le plateau",
  // Preview
  recenter: "Recentrer la vue",
  webglUnavailable: "Aperçu 3D indisponible : WebGL est désactivé dans ce navigateur.",
  // Settings panel
  settings: "Réglages",
  close: "Fermer",
  dimensions: "Dimensions",
  cells: (columns: number, rows: number) => `${columns} × ${rows} cellules`,
  height: "hauteur",
  size: "Taille",
  columns: "Colonnes",
  fewerColumns: "Une colonne de moins",
  moreColumns: "Une colonne de plus",
  rows: "Rangées",
  fewerRows: "Une rangée de moins",
  moreRows: "Une rangée de plus",
  pocketProfile: "Profil de poche",
  hybrid: "Hybride",
  hybridDescription: "Muret de 0,35 mm : le bac est bien assis sur ses pentes, sans jeu.",
  flush: "Ras",
  flushDescription: "Sans le muret de 0,35 mm : baseplate plus fine.",
  recommended: "Recommandé",
  soon: "Bientôt",
  // Download
  downloadStl: "Télécharger le STL",
  preparingStl: "Préparation du STL…",
  // Errors
  computeFailed: "Le calcul de la baseplate a échoué. Modifiez un réglage pour réessayer.",
  exportFailed: "L'export STL a échoué. Réessayez.",
};
