import { BRAND_ACCENT_NAME } from "@repo/ui";

/**
 * Interface copy, worded with the glossary (CONTEXT.md). French only for now: English and
 * language switching arrive with #14.
 */
export const strings = {
  locale: "fr-FR",
  generator: "Générateur de baseplates",
  // Top bar and menu
  share: "Partager",
  reset: "Réinitialiser",
  donate: "Offrir un café",
  comingSoon: "Bientôt disponible",
  newTab: "s'ouvre dans un nouvel onglet",
  parameters: "Paramètres",
  menu: "Menu",
  actions: "Actions",
  linkCopied: "Lien copié",
  copyFailed: "Copie impossible : copiez le lien ci-dessous.",
  resetTitle: "Réinitialiser les réglages ?",
  resetDescription:
    "La baseplate revient aux réglages par défaut. Vos paramètres sont conservés : buse, hauteur de couche, largeur de ligne, plateau et couleur de l'aperçu.",
  cancel: "Annuler",
  previewColor: "Couleur de l'aperçu",
  previewColors: {
    brand: BRAND_ACCENT_NAME.fr,
    white: "Blanc",
    pebble: "Galet",
    graphite: "Graphite",
    sand: "Sable",
  },
  print: "Impression",
  nozzle: "Buse",
  nozzleHint: "Choisir une buse règle la largeur de ligne sur son diamètre.",
  layerHeight: "Hauteur de couche",
  thinnerLayer: "Couche plus fine",
  thickerLayer: "Couche plus épaisse",
  lineWidth: "Largeur de ligne",
  narrowerLine: "Ligne plus fine",
  widerLine: "Ligne plus large",
  buildPlate: "Plateau",
  buildPlateHint: "Surface utile du plateau de votre imprimante.",
  buildPlateWidth: "Largeur du plateau",
  narrowerPlate: "Plateau moins large",
  widerPlate: "Plateau plus large",
  buildPlateDepth: "Profondeur du plateau",
  shallowerPlate: "Plateau moins profond",
  deeperPlate: "Plateau plus profond",
  // Statistics
  statistics: "Statistiques",
  statCells: "Cellules",
  statMargin: "Marge",
  statHeight: "Hauteur",
  statVolume: "Matière",
  statScrews: "Vis",
  statPieces: "Pièces",
  none: "aucune",
  computing: "calcul en cours",
  layers: (count: number, layerHeight: string) => `${count} couches de ${layerHeight} mm`,
  margins: (left: string, right: string, back: string, front: string) =>
    `gauche ${left}, droite ${right}, arrière ${back}, avant ${front} mm`,
  fits: "tient",
  doesNotFit: "ne tient pas",
  plateTooSmall: (plate: string) =>
    `La baseplate dépasse votre plateau (${plate}) dans les deux sens. Réduisez-la, ou corrigez la taille du plateau dans les paramètres.`,
  plateTooSmallShort: "Ne tient pas sur le plateau",
  narrowMargin: (margin: string, lines: string) =>
    `Une marge de ${margin} mm est plus étroite que deux largeurs de ligne (${lines} mm) : elle s'imprimera mal. Élargissez-la ou supprimez-la.`,
  // Preview
  recenter: "Recentrer la vue",
  webglUnavailable: "Aperçu 3D indisponible : WebGL est désactivé dans ce navigateur.",
  // Settings panel
  settings: "Réglages",
  close: "Fermer",
  dimensions: "Dimensions",
  cells: (columns: number, rows: number) => `${columns} × ${rows} cellules`,
  height: "hauteur",
  size: "Taille",
  sizeMode: "Mode de taille",
  sizeDrawer: "Tiroir",
  sizeCells: "Nombre de cellules",
  drawerHint: "Cotes intérieures du tiroir : la baseplate le remplit.",
  drawerWidth: "Largeur",
  narrowerDrawer: "Tiroir moins large",
  widerDrawer: "Tiroir plus large",
  drawerDepth: "Profondeur",
  shallowerDrawer: "Tiroir moins profond",
  deeperDrawer: "Tiroir plus profond",
  marginWidth: "Marge en largeur",
  lessMarginWidth: "Moins de marge en largeur",
  moreMarginWidth: "Plus de marge en largeur",
  marginDepth: "Marge en profondeur",
  lessMarginDepth: "Moins de marge en profondeur",
  moreMarginDepth: "Plus de marge en profondeur",
  withMargin: (width: string, depth: string) => `marge ${width} × ${depth} mm`,
  withoutMargin: "sans marge",
  alignment: "Alignement",
  alignmentHint: "Où placer la grille quand la marge ne tombe pas juste : la marge prend le reste.",
  alignments: {
    tl: "Arrière gauche",
    t: "Arrière",
    tr: "Arrière droite",
    l: "Gauche",
    c: "Centre",
    r: "Droite",
    bl: "Avant gauche",
    b: "Avant",
    br: "Avant droite",
  },
  advanced: "Avancé",
  drawerGap: "Jeu au tiroir",
  lessGap: "Moins de jeu",
  moreGap: "Plus de jeu",
  drawerGapHint: "Retiré à la largeur et à la profondeur du tiroir, pour que la baseplate y entre sans forcer.",
  gapSummary: (gap: string) => `Jeu au tiroir ${gap} mm`,
  columns: "Colonnes",
  fewerColumns: "Une colonne de moins",
  moreColumns: "Une colonne de plus",
  rows: "Rangées",
  fewerRows: "Une rangée de moins",
  moreRows: "Une rangée de plus",
  pocketProfile: "Profil de poche",
  hybrid: "Hybride",
  hybridDescription: "Muret de 0,35 mm : le bac est bien assis sur ses pentes, sans jeu.",
  flush: "Ras",
  flushDescription: "Sans le muret de 0,35 mm : baseplate plus fine.",
  recommended: "Recommandé",
  soon: "Bientôt",
  // Download
  download: { "3mf": "Télécharger le 3MF", stl: "Télécharger le STL" },
  preparing: { "3mf": "Préparation du 3MF…", stl: "Préparation du STL…" },
  otherFormats: "Autres formats",
  threeMfDescription: "Recommandé : s'ouvre dans le trancheur, avec le lien de ses réglages.",
  stlDescription: "Pour les trancheurs qui ne lisent pas le 3MF.",
  // Errors
  computeFailed: "Le calcul de la baseplate a échoué. Modifiez un réglage pour réessayer.",
  exportFailed: "Le téléchargement a échoué. Réessayez.",
};
